fixtures:
  repositories:
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    stdlib:  "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "https://github.com/camptocamp/puppet-systemd.git"
    mysql_java_connector: "https://github.com/voxpupuli/puppet-mysql_java_connector.git"
    augeas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
